version: '3'

services:
  stable-diffusion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stable-diffusion
    restart: unless-stopped
    command: bash -c "python download_weights.py --mock && python app.py"
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]